targets:
  - kmers
  - assembly
  - alignment
  - triobin


tmpdir: '/tmp'


# only required if parental short reads are in CRAM format
cram_ref: "path/to/cram/reference.fasta"


# required for assembly stats and alignment
ref:
  shortname: "GRCh38"
  fasta: "path/to/alignment/reference.fasta"
  index: "path/to/alignment/reference.fasta.fai"


# run HG002 trio with parental short reads (default)
HG002_sr:
  child:
    id: HG002
    reads:
      - /path/to/HG002/HiFi/reads.bam # 1+ bam and/or fastq.gz files
      - /path/to/HG002/HiFi/reads.fastq.gz # 1+ bam and/or fastq.gz files
  father:
    id: HG003
    reads:
      - /path/to/HG003/paired_end/reads_R1.fastq.gz # 1+ bam and/or cram and or fastq.gz (set of R1/R2) files
      - /path/to/HG003/paired_end/reads_R2.fastq.gz # 1+ bam and/or cram and or fastq.gz (set of R1/R2) files
  mother:
    id: HG004
    reads:
      - /path/to/HG004/paired_end/reads.bam # 1+ bam and/or cram and or fastq.gz (set of R1/R2) files
      - /path/to/HG004/paired_end/reads.cram # 1+ bam and/or cram and or fastq.gz (set of R1/R2) files


# run HG002 trio with parental hifi
HG002_hifi:
  child:
    id: HG002
    reads:
      - /path/to/HG002/HiFi/reads.bam # 1+ bam and/or fastq.gz files
      - /path/to/HG002/HiFi/reads.fastq.gz # 1+ bam and/or fastq.gz files
  father:
    id: HG003
    reads:
      - /path/to/HG003/HiFi/reads.bam # 1+ bam and/or fastq.gz files
      - /path/to/HG003/HiFi/reads.fastq.gz # 1+ bam and/or fastq.gz files
  mother:
    id: HG004
    reads:
      - /path/to/HG004/HiFi/reads.bam # 1+ bam and/or fastq.gz files
      - /path/to/HG004/HiFi/reads.fastq.gz # 1+ bam and/or fastq.gz files
  parent_reads: hifi